### ISSUE TITLE
Has an error after regularly rerouting when define some points.

### ISSUE THREAD

**Issue by mrfyo** [openTCS/opentcs#105]
## Affected version

5.11.0

...

## Steps to reproduce

_How can the incorrect behaviour be reproduced?_

1. define some report points.
2. create one trnaport order that its route will pass these report points.
3. regularly reroute  this vehicle after this vehicle has passed the first report point.

### Expected behaviour

_What would be the correct/expected behaviour?_

its will complete this transport order.

### Actual behaviour

_What behaviour can actually be observed instead of the correct behaviour?_

![image](https://github.com/openTCS/opentcs/assets/39879471/1cf6b011-1779-456f-a444-decdcc3006d9)

### Additional information

_Other data that can help with fixing the defect, e.g. logs, screenshots etc._

* Operating system and version: Windows 11
* Java distribution version: Oracle Java Runtime Environment 13
* is or not exists bug in DefaultVehicleController.discardSentFutureCommands? <b> It seems that too many commands were removed from the futureCommands<b>.

**Comment by swltr** [comment]
@mrfyo Thanks for reporting this! The issue has been fixed in 5.11, which was released yesterday. Please give it a try!
