### ISSUE TITLE
How to deploy Swagger so that I can see the API interface doc？

### ISSUE THREAD

**Issue by zhaoboyuye** [openTCS/opentcs#133]
### Discussed in https://github.com/orgs/openTCS/discussions/132

<div type='discussions-op-text'>

<sup>Originally posted by **zhaoboyuye** February 28, 2024</sup>
I have now completed the deployment of opentcs kernel and accessed the project http://localhost:55200/v1 What should I do if I return 404 without returning to the Swagger interface page?</div>

**Comment by swltr** [comment]
@zhaoboyuye There is no "Swagger interface page". The OpenAPI specification can be found in the `openTCS-Documentation/` directory of the openTCS distribution. You can also find it at https://opentcs.org/docs/5.13/index.html.

**Comment by zhaoboyuye** [comment]
openTCS-Documentation/ can it run?

**Comment by swltr** [comment]
Your question is unclear.

**Comment by zhaoboyuye** [comment]
penTCS-Documentation/ directory Can it run？

**Comment by swltr** [comment]
@zhaoboyuye It is still unclear what your actual problem is here. The documentation cannot "run". It is documentation, i.e. it is to be read.
