### ISSUE TITLE
Load vehicle allowOrderType while kernel startup

### ISSUE THREAD

**Issue by z29591259** [openTCS/opentcs#149]
Currently, the vehicle's allowOrderType can only be configured in the OperationDesk and cannot be set in the ModelEditor. 
If the Kernel is restarted, the vehicle's allowOrderType will revert to '*', resulting in the dispatch not using the expected vehicle.

So, I hope to write the allowOrderType into the Map file, so that the Kernel can automatically read this value upon startup. 

May I ask what considerations were behind the initial design? 

Is there currently a way to achieve my goal? 

Thank you.

![Snipaste_2024-06-11_22-49-04](https://github.com/openTCS/opentcs/assets/25024958/495a98f6-5015-46dc-a8fa-5ad3ef88b66b)

![Snipaste_2024-06-11_22-50-36](https://github.com/openTCS/opentcs/assets/25024958/25d415f1-505c-4b81-8015-37ce3da442c8)

**Comment by swltr** [comment]
@z29591259 When order types - previously named categories - were introduced with openTCS 4.8, the goal was to have a _dynamic_ filter criterion when matching vehicles with transport orders. In case openTCS was restarted, the allowed order types would be set again via the API. Persisting the types in openTCS was not a requirement, so it was not implemented.

I do not see anything blocking an implementation of persisting and materializing this information, other than the plain fact that it is work that somebody would need to do.
