### ISSUE TITLE
there is some problem with bezier path

### ISSUE THREAD

**Issue by vincentknw** [openTCS/opentcs#24]
## Affected version

release 5.5.0

## Steps to reproduce

add a new bezier path in model editor

### Expected behaviour
coordinate of control point consistent with coordinate system of Point  

### Actual behaviour

coordinate of control point is wrong , y axis in the opposite direction and value is not consistent with Point

### Additional information

* Operating system and version: _e.g. Ubuntu Linux 20.04, Windows 10, ..._
* Java distribution version: _e.g. Oracle Java Runtime Environment 11_
* ...

**Comment by martingr** [comment]
Hi @vincentknw, the behavior you observed is actually the expected one. Please refer to #13 for an explanation on how control point coordinates are defined.
