### ISSUE TITLE
withdrawn an order from order sequence result error

### ISSUE THREAD

**Issue by sehb** [openTCS/opentcs#27]
## Affected version

release 5.5.0
...

## Steps to reproduce

Step 1: Create an order sequence;
Step 2: Add an order to the sequence;
Step 3: After the order goes into "BEGING_PROCESSED" , withdrawn the order;
And now, the order state is always in "BEGING_PROCESSED" state and cannot go into a "WITHDRAWN" state.
After that,  the vehicle can not process any new order.

### Expected behaviour

_What would be the correct/expected behaviour?_

...

### Actual behaviour

_What behaviour can actually be observed instead of the correct behaviour?_

...

### Additional information

_Other data that can help with fixing the defect, e.g. logs, screenshots etc._

* Operating system and version: _e.g. Ubuntu Linux 20.04, Windows 10, ..._
* Java distribution version: _e.g. Oracle Java Runtime Environment 13_
* ...

**Comment by sehb** [comment]
We found that there was a problem with the interaction between the drive adapter and the AGV, causing the cancellation to fail. We fixed the issue and it doesn't reappear so far, thanks!

**Comment by swltr** [comment]
@sehb I hadn't gotten to properly check on this issue, yet. Thank you for your update!
