### ISSUE TITLE
Published Events no longer have Type info even though it is in the documentation

### ISSUE THREAD

**Issue by jfaigan** [openTCS/opentcs#77]
## Affected version

_Name the affected version, i.e. "release x.y.z" or "revision <HASH>"._
5.7.0
...

## Steps to reproduce

_How can the incorrect behaviour be reproduced?_

1. Use the API to listen to the Events
2. Type element is missing from all types (TransportOrder, Vehicle and PeripheralJob)
3. ...

### Expected behaviour

_What would be the correct/expected behaviour?_

Type element should be provided as per the API documentation

### Actual behaviour

_What behaviour can actually be observed instead of the correct behaviour?_

Type element is not in the returned json

### Additional information

_Other data that can help with fixing the defect, e.g. logs, screenshots etc._
![image](https://user-images.githubusercontent.com/14929031/219869496-d9aed117-ecf0-4a1b-ae6b-8ee2aec5e612.png)
![image](https://user-images.githubusercontent.com/14929031/219869517-9eb65ff8-50db-40c1-8fd2-3a79cd0e768a.png)

* Operating system and version: _e.g. Ubuntu Linux 20.04, Windows 10, ..._
* Java distribution version: _e.g. Oracle Java Runtime Environment 13_
![image](https://user-images.githubusercontent.com/14929031/219869478-2b03d655-fb3e-423b-b54f-9855d9331758.png)

**Comment by swltr** [comment]
@jfaigan Thanks for the report! I assume this still worked with 5.6.0?

**Comment by jfaigan** [comment]
> 

No problem.  Yes, I have both 5.6 and 5.7 running in parallel on different ports.

Here is what 5.6 yields:
![image](https://user-images.githubusercontent.com/14929031/220115594-fdb03b9e-5372-4b7e-a989-edbf273d5e65.png)

**Comment by swltr** [comment]
This has been fixed with b3a80d1b767f90a7790ac378d7e88107d1ad5482 for 5.8, which we can hopefully finalize real soon now.
