### ISSUE TITLE
Rename root project name or change this git repo name.

### ISSUE THREAD

**Issue by bourne7** [openTCS/opentcs#90]
In settings.gradle:1 we have:

```
rootProject.name = 'openTCS'
```

if we clone this repo to local dir, we use 
```
git clone https://github.com/openTCS/opentcs.git
```

which will create a dir `opentcs` in local dir.  Well, we will have this issue when compile with gradle embedded in idea 2023.1

```
gradle java.lang.IllegalStateException: Module entity with name: opentcs should be available
```

I found the solution here: https://youtrack.jetbrains.com/issue/IDEA-317606/

I  rename this folder from opentcs to openTCS and problem solved!

I think you can do one of the following steps:

1. Add comment to readme file to tell user clone to a folder named openTCS
2. change this repo name to openTCS
3. change rootProject.name to openTCS

thanks 😉

**Comment by swltr** [comment]
@bourne7 I'd consider this a problem with IntelliJ, not with the openTCS project. According to our observations, this isn't a problem any more with more recent IntelliJ versions, so I'm closing the issue.
